[build]
builder = "nixpacks"

[[services]]
name = "backend"
directory = "."
startCommand = "uvicorn api:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/health"
healthcheckTimeout = 100
port = 8000

[[services]]
name = "frontend"
directory = "dockeeper-web"
buildCommand = "npm install && npm run build"
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
port = 3000
env = ["NODE_VERSION=18", "PORT=3000"] 